name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  dio: ^5.1.1
  flutter:
    sdk: flutter
 
  
dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  carousel_slider:
      git:
        url: https://github.com/serenader2014/flutter_carousel_slider 
        ref: master
flutter:
  uses-material-design: true
  assets: 
  - assets/
  - assets/images/
